name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    # We will use the latest macos runner, which currently has Xcode 15.x/iOS 17.x or Xcode 16.x/iOS 18/26.x
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v6
        with:
            fetch-depth: 0
            
      - uses: ruby/setup-ruby@v1
        with:
          # Do not use 3.4, won't work due to kconv library not included
          ruby-version: '3.2' # Not needed with a .ruby-version, .tool-versions or mise.toml
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          
      - name: ðŸ› ï¸ Create and Prepare Simulator Device
        id: create_simulator
        run: |
          # 1. Define the desired device name and type
          DEVICE_NAME="CodecovTestSimulator"
          DEVICE_TYPE="iPhone 15 Pro" # A reliable device type

          # 2. Get the latest available iOS Simulator Runtime ID (e.g., com.apple.CoreSimulator.SimRuntime.iOS-18-0)
          # This ensures we use a runtime that is guaranteed to be available on the runner.
          RUNTIME_ID=$(xcrun simctl list runtimes | grep -m 1 -E 'iOS|visionOS' | awk -F '[()]' '{print $2}')
          
          echo "Found Runtime ID: $RUNTIME_ID"
          
          # 3. Delete the device if it exists (for safety in edge cases)
          xcrun simctl delete "$DEVICE_NAME" 2>/dev/null
          
          # 4. Create the new simulator instance
          DEVICE_ID=$(xcrun simctl create "$DEVICE_NAME" "$DEVICE_TYPE" "$RUNTIME_ID")
          
          echo "Created Simulator ID: $DEVICE_ID"
          
          # 5. Export the name to be used in the xcodebuild command
          echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV

      - name: ðŸ—ï¸ Build and test, collect coverage
        # Now we use the environment variable $DEVICE_NAME to target the device we just created.
        run: xcodebuild clean build test -project CodecovDemo.xcodeproj -scheme CodecovDemo -destination "platform=iOS Simulator,name=${{ env.DEVICE_NAME }}" -enableCodeCoverage YES
      
      - name: Convert xcresult coverage to SonarQube coverage format
        run:  bundle exec slather coverage --sonarqube-xml --scheme CodecovDemo ./CodecovDemo.xcodeproj
        
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -X

      # - name: Upload SonarQube Coverage Artifact
      #   uses: actions/upload-artifact@v5
      #   with:
      #     name: sonarqube-coverage-xml
      #     path: sonarqube-generic-coverage.xml
      #     retention-days: 7  # Optional: Set retention for a short period (default is 90 days)
